language: java

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "chave_da_organização"
    token:
      secure: "token_de_segurança"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: "chave_de_acesso_do_heroku"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
