language: java

jdk:
  - openjdk11

before_install:
- chmod +x mvnw

addons:
  sonarcloud:
    organization: mateuscppoi-github
    token:
      secure: v1mNx0Gfb0ZeVyTNFntXmUXR0W9h4wJhinKnnHh30QSiAoSH9rx7HqaQm55Z7bZf3xvVWXVFA0gULvAe9E1ud05+bgM2WUTEibyiihGnuJWZtDL5nS5NNHZ0Moq93aCWu+cbWTctrkTH7/BMuN5oDnKJ4+mHEgG1ySgx++CJvkRglPIHH9NtZA1YdRPKt7mAfL78Xb0u8lJyXb9zzuU4l69FfR2jo51k8Wa9u1o7I5WkDzP87vnMw3bSFmh3hABPv3fO6kwhm+RmCo2Hh94pHbbVJ9yhZGD7mb/VPJSYBgKkNmjhJOGe/NtBZQPIlFkVI1f82X9FoeLKpnpMrnIz/pmrVt2y0AHjcTUV6iaml3Tjtjo8R7SyqvFQq5eg07eCSp74O7hYGg6GsyM7RikMGnsG0t4IzMiwGTz7foQGbvHA6tL4+80tPZLyes5+Fu4TyK7T0l1193TtdrfJLlD5NlA32SzkAhzlGTr3EFTisSS/nSIwAviXyp/RlMoN9/yCM90Wle+4qCb9Gb4vGn3r3gHN1mq1KoKhqzrGmPejnKluqNHIcICMOudijKBcjlCPrHjuuBtYEnM0wtnC5jkZTjlNfNTwTTpF5r6hYfBhcoBVg+8BS+ePr9KFlHslwh/TCuBSbfLyloEwyrqgS5G4hhTZW+LC9eEyEmOdMD7fRwU=

script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: goZZT0HNYGDj8zdxeKaeOCbNM4KxK2gOyrjTjE9T1TOP19VE2dWEl0s95ftd9W+l+XLcBvkdCeObPMoD45rXOQFG/S7I8J/N5dvOtYv3Z2Ef8EvPISyx9bb5hoVL/juFB4hkVv3Gu/00lgfcjKnntC+qfBjBBrC1Onyx6jNzrWg5mO+AGWXczfazb7eK1v1xi7CMkbkVr4q6ylvjQ3XN9pkq6MMDgRp5+MZIkq57qKF8Z+ftMrwVZKzRXw8goTYzQn6Ic8HzfOxIX56pcJdhjU3OreW6nzJIvYm/2zXEIo77mGI6YFiJQ1ShggtZ+I01JA4k4ihv4htimvyUlbdJnN+2cuQizgFnA1aTDgTbOKJZd0PkAci+1RZT0fbsxwaghs2Ni7vquIBpmVKYZtTXc+t9N0K8qWC7DoRhXUyNej3deRUSnZoq6hiRzRoNCQVsCut4gRz/415cob54P2J4zViy0HWUngKcycQu6JQwFB0pzQiIfWVk4JRtCwzIv5zodC6tkJQRGu0oY5qQZq8pzzbbfhtPa6AhjHYgXEjsP2aWjVukIErw6K7lzY4OZGKFFrs83RMMOU5mODIXxM8rzxj/FZdO4o0wbUYjOoaneY9rbldKugHuYEl/x3kRyrOwxfiSrfuRRoEgOc1QqIi/U1NMvZ87O4+zq+b2xd9E1zE=

cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"

