language: java

before_install:
  - chmod +x mvnw

addons:
  sonarcloud:
    organization: "mateuscppoi-github"
    token:
      secure: "2d64b2491f2b7143559f9c20ae13228738999dbb"

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

deploy:
  provider: heroku
  skip_cleanup: true
  api_key: "282ad78d-048b-4a86-a23c-01e6304acc4d"


cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
